/**
 * Delete old ATIPICO separate datasets from Firebase.
 * These have been merged into the main CSV files.
 *
 * Run: node scripts/deleteOldDatasets.mjs
 */

import { initializeApp } from 'firebase/app';
import { getFirestore, doc, deleteDoc, collection, getDocs } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyDQ_pdzqlEXZZOhe7poiv-wkgoUNg3Bqag",
  authDomain: "ultranalytics-8582c.firebaseapp.com",
  projectId: "ultranalytics-8582c",
  storageBucket: "ultranalytics-8582c.firebasestorage.app",
  messagingSenderId: "306745766555",
  appId: "1:306745766555:web:aa1cc6556f51dbd75c0c3e"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Dataset IDs generated by uploadOldPlatform.mjs:
// ds_old_${eventName.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40)}
const DS_IDS = [
  'ds_old_ATIPICO_W_MATTIAS_CLAY___EDO_ANTONELLO_9',
  'ds_old_ATIPICO_W_MATTIA_FONTANA_14_12_24',
  'ds_old_ATIPICO_22_03_25',
  'ds_old_ATIPICO_ANNIVERSARY_TOO_LATE_CLOSING_PAR',
];

async function deleteDataset(dsId) {
  // Delete all chunks in records subcollection
  const recordsRef = collection(db, 'datasets', dsId, 'records');
  const snapshot = await getDocs(recordsRef);

  let chunkCount = 0;
  for (const docSnap of snapshot.docs) {
    await deleteDoc(docSnap.ref);
    chunkCount++;
  }

  // Delete the dataset document itself
  await deleteDoc(doc(db, 'datasets', dsId));

  return chunkCount;
}

async function main() {
  console.log('Eliminazione dataset ATIPICO separati da Firebase...\n');

  for (const dsId of DS_IDS) {
    try {
      const chunks = await deleteDataset(dsId);
      console.log(`  Eliminato: ${dsId} (${chunks} chunk)`);
    } catch (e) {
      console.log(`  Errore su ${dsId}: ${e.message}`);
    }
  }

  console.log('\nCompletato! I dati ATIPICO sono ora solo nei CSV principali.');
  process.exit(0);
}

main().catch(e => {
  console.error('Errore:', e);
  process.exit(1);
});
